/*
Copyright 2026 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Package v1 implements the SLSA build type of krel runs. The build type
// is defined in docs/krel/buildtypes/v1, which holds the schema of the
// parameters recorded in the provenance attestations generated by krel.
package v1

// BuildType is the URI identifying the build type of a krel run. It
// is recorded in the buildDefinition.buildType field of the provenance
// and resolves to the directory defining the build type.
const BuildType = "https://git.k8s.io/release/docs/krel/buildtypes/v1"
