---
project_name: kubernetes-release

env:
  - CGO_ENABLED=0
  - COSIGN_YES=true

before:
  hooks:
    - go mod tidy
    - git diff --exit-code go.mod go.sum

gomod:
  proxy: true

builds:
  - id: krel
    no_unique_dist_dir: true
    main: ./cmd/krel
    binary: krel-{{ .Arch }}-{{ .Os }}
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
  - id: release-notes
    no_unique_dist_dir: true
    main: ./cmd/publish-release
    binary: release-notes-{{ .Arch }}-{{ .Os }}
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - id: krel
    format: binary
    allow_different_binary_count: true
    name_template: krel-{{ .Arch }}-{{ .Os }}
  - id: release-notes
    format: binary
    allow_different_binary_count: true
    name_template: release-notes-{{ .Arch }}-{{ .Os }}

signs:
  - id: keyless
    signature: "${artifact}.sig"
    certificate: "${artifact}.pem"
    cmd: cosign
    args: ["sign-blob", "--output-signature", "${artifact}.sig", "--output-certificate", "${artifact}.pem", "${artifact}"]
    artifacts: all

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

release:
  github:
    owner: kubernetes
    name: release
  prerelease: auto

changelog:
  skip: true
