#!/usr/bin/env bash

# Copyright 2019 The Kubernetes Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -e
set -u
set -o pipefail

setup_env() {
  if [ -n "${GOBIN:-}" ]
  then
    export PATH="${PATH}:${GOBIN}"
  fi
}

install_dep() {
  (
    go get -d -u github.com/golang/dep
    cd "${GOPATH}/src/github.com/golang/dep"
    DEP_LATEST="$(git describe --abbrev=0 --tags)"
    git checkout "${DEP_LATEST}" >/dev/null 2>&1
    go install -ldflags="-X main.version=${DEP_LATEST}" ./cmd/dep
  )
}

check_deps() {
  # Make sure our deps are not out-dated
  dep ensure -update
  status="$(git status -s)"

  [ -z "${status}" ] || {
    echo "dependencies are out of date:"
    # shellcheck disable=SC2001
    echo "${status}" | sed 's/^/  /g'

    # Should we stop here or should we just go ahead, try to compile and hope
    # for the best?
    # exit 1
  }
}

compile() {
  local tool="$1"

  go install "${tool}"
  echo "${tool} compiled & installed"
}

main() {
  setup_env
  install_dep
  check_deps

  compile k8s.io/release/cmd/blocking-testgrid-tests
}

main "$@"
