#!/usr/bin/env bash

# Copyright 2019 The Kubernetes Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -e
set -u
set -o pipefail

setup_env() {
  if [ -n "${GOBIN:-}" ]
  then
    export PATH="${PATH}:${GOBIN}"
  fi
}

compile() {
  local tool="$1"

  go install "${tool}"
  echo "${tool} compiled & installed"
}

check_deps() {
  compile github.com/psampaz/go-mod-outdated

  local gmo_args=( '-update' '-direct' )
  if [ -n "${FAIL_ON_OUTDATED:-}" ]; then
    gmo_args+=( '-ci' )
  fi

  go list -u -m -json all | go-mod-outdated "${gmo_args[@]}"
}

main() {
  cd "$(dirname "${BASH_SOURCE[0]}")"

  setup_env
  check_deps

  compile k8s.io/release/cmd/blocking-testgrid-tests
}

main "$@"
