#!/usr/bin/env bash

# Copyright 2019 The Kubernetes Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -e
set -u
set -o pipefail

RELEASE_TOOLS=(
  blocking-testgrid-tests
  kubepkg
  release-notes
)

setup_env() {
  echo "Setting up environment..."

  if [ -n "${GOBIN:-}" ]
  then
    export PATH="${PATH}:${GOBIN}"
  fi
}

compile() {
  local tool="$1"

  echo "Compiling $tool..."

  go install "${tool}"
  echo "${tool} compiled & installed"
}

check_deps() {
  echo "Checking dependencies..."

  compile github.com/psampaz/go-mod-outdated

  local gmo_args=( '-update' '-direct' )
  if [ -n "${FAIL_ON_OUTDATED:-}" ]; then
    gmo_args+=( '-ci' )
  fi

  go list -u -m -json all | go-mod-outdated "${gmo_args[@]}"
}

compile_krel() {
  local git_tree_state
  local pkg

  git_tree_state=clean
  pkg=k8s.io/release/pkg/version

  if git status --porcelain --untracked-files=no; then
    git_tree_state=dirty
  fi

  go build -ldflags "-s -w \
    -X $pkg.buildDate=$(date -u +'%Y-%m-%dT%H:%M:%SZ') \
    -X $pkg.gitCommit=$(git rev-parse HEAD) \
    -X $pkg.gitTreeState=$git_tree_state \
    -X $pkg.gitVersion=$(git describe --abbrev=0)" \
    -o "$GOPATH"/bin/krel ./cmd/krel
}

main() {
  cd "$(dirname "${BASH_SOURCE[0]}")"

  setup_env
  check_deps

  if [ $# -gt 0 ]; then
    for tool in "$@"; do
      compile "k8s.io/release/cmd/${tool}"
    done
  else
    for tool in "${RELEASE_TOOLS[@]}"; do
      echo "Compiling default release tools..."
      compile "k8s.io/release/cmd/${tool}"
    done
    compile_krel
  fi
}

main "$@"
