# Copyright 2019 The Kubernetes Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM golang:1.16.4 AS builder

ENV GO111MODULE=on

WORKDIR /workspace

COPY . .

RUN go build -o . ./cmd/kubepkg/...


FROM fedora:30

RUN dnf install -y \
      rpm-build \
      rpmdevtools \
      createrepo \
    && dnf clean all

RUN useradd builder -u 9000 -m -s /bin/false

USER builder

RUN mkdir /home/builder/workspace

WORKDIR /home/builder/workspace

RUN rpmdev-setuptree

COPY --chown=builder:builder ./cmd/kubepkg/templates ./templates
COPY --from=builder --chown=builder:builder /workspace/kubepkg .

ENTRYPOINT ["./kubepkg", "rpms"]
