#!/bin/sh
set -eu

# Set CEPH_CONF so `rbd` doesn't try to look in /etc/ceph and error out
export CEPH_CONF="$SNAP_USER_DATA/ceph/ceph.conf"

if [ -e /root/cdk/kube.env ]; then
    set -a  # enable auto-export
    . /root/cdk/kube.env
    set +a  # disable auto-export
fi

exec "$SNAP/kube-controller-manager" "$@"
