#!/bin/sh
set -eu

# Set CEPH_CONF so `rbd` doesn't try to look in /etc/ceph and error out
export CEPH_CONF="$SNAP_USER_DATA/ceph/ceph.conf"

if [ -e "$SNAP_COMMON/environment" ]; then
    set -a  # enable auto-export
    . "$SNAP_COMMON/environment"
    set +a  # disable auto-export
fi

exec "$SNAP/kube-controller-manager" "$@"
