#! /bin/bash

# cni
go run build.go -arch amd64 -distro_name xenial -package kubernetes-cni -version 0.0.1

# 1.3.6
go run build.go -arch amd64 -distro_name xenial -package kubelet -version 1.3.6
go run build.go -arch amd64 -distro_name xenial -package kubectl -version 1.3.6

# 1.4.0-beta.0
go run build.go -arch amd64 -distro_name xenial -package kubelet -version 1.4.0-beta.0
go run build.go -arch amd64 -distro_name xenial -package kubectl -version 1.4.0-beta.0
