#!/bin/sh
set -eu

export HOME="/root"

if [ -e "$SNAP_COMMON/environment" ]; then
    set -a  # enable auto-export
    . "$SNAP_COMMON/environment"
    set +a  # disable auto-export
fi

exec "$SNAP/kubelet" "$@"
