timeout: 14400s
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/github-token/versions/latest
      env: GITHUB_TOKEN

steps:
  - name: gcr.io/cloud-builders/git
    dir: "go/src/k8s.io"
    args:
      - "clone"
      - "https://github.com/${_TOOL_ORG}/${_TOOL_REPO}"

  - name: gcr.io/cloud-builders/git
    entrypoint: "bash"
    dir: "go/src/k8s.io/release"
    args:
      - "-c"
      - |
        git fetch
        echo "Checking out ${_TOOL_REF}"
        git checkout ${_TOOL_REF}

  - name: gcr.io/k8s-staging-releng/k8s-cloud-builder:${_KUBE_CROSS_VERSION}
    dir: go/src/k8s.io/release
    env:
      - KREL_OUTPUT_PATH=/workspace/bin/krel
      - "TOOL_ORG=${_TOOL_ORG}"
      - "TOOL_REPO=${_TOOL_REPO}"
      - "TOOL_REF=${_TOOL_REF}"
      - "FORCE_BUILD_KREL=${_FORCE_BUILD_KREL}"
    args:
      - ./hack/get-krel

  - name: gcr.io/k8s-staging-releng/k8s-cloud-builder:${_KUBE_CROSS_VERSION}
    dir: "/workspace"
    env:
      - "TOOL_ORG=${_TOOL_ORG}"
      - "TOOL_REPO=${_TOOL_REPO}"
      - "TOOL_REF=${_TOOL_REF}"
      - "K8S_ORG=${_K8S_ORG}"
      - "K8S_REPO=${_K8S_REPO}"
      - "K8S_REF=${_K8S_REF}"
    secretEnv:
      - GITHUB_TOKEN
    args:
      - "bin/krel"
      - "fast-forward"
      - "--log-level=${_LOG_LEVEL}"
      - "--non-interactive"
      - "--github-org=${_K8S_ORG}"
      - "--github-repo=${_K8S_REPO}"
      - "${_NOMOCK}"

tags:
  - ${_GCP_USER_TAG}
  - ${_NOMOCK_TAG}
  - FAST_FORWARD
  - ${_GIT_TAG}
  - ${_RELEASE_BRANCH}
  - ${_TYPE_TAG}
  - ${_K8S_ORG}
  - ${_K8S_REPO}
  - ${_TYPE}

options:
  pool:
    name: "projects/$PROJECT_ID/locations/us-central1/workerPools/c3-highcpu-44"

substitutions:
  # _GIT_TAG will be filled with a git-based tag of the form vYYYYMMDD-hash, and
  # can be used as a substitution
  _GIT_TAG: "12345"
