---
name: test-snapshot-release

on:
  pull_request:
    branches:
      - master

permissions: {}

jobs:
  snapshot:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          disable-sudo: true
          egress-policy: audit

      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v3.5.2
        with:
          fetch-depth: 1
          persist-credentials: false

      - name: Set up Go
        id: go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: go.mod
          check-latest: true
          cache: false

      - name: Install bom
        uses: kubernetes-sigs/release-actions/setup-bom@c130b4494862d330a1aa4de320076c666d0708da # v0.4.4

      - name: Test release build
        uses: goreleaser/goreleaser-action@f06c13b6b1a9625abc9e6e439d9c05a8f2190e94 # v7.2.3
        with:
          args: release --clean --snapshot --skip=sign
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: check binary
        run: |
          ./dist/krel-amd64-linux version
          ./dist/publish-release-amd64-linux help
          ./dist/release-notes-amd64-linux version

      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: artifacts
          path: dist/*

  attestation:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    needs:
      - snapshot

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          disable-sudo: true
          egress-policy: audit

      - name: Check out code onto GOPATH
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 1
          persist-credentials: false

      - name: Install tejolote
        uses: kubernetes-sigs/release-actions/setup-tejolote@c130b4494862d330a1aa4de320076c666d0708da # v0.4.4

      - run: |
          tejolote attest github://kubernetes/release/"${GITHUB_RUN_ID}" --output release.intoto.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: release.intoto.json
          path: ./release.intoto.json
